### PR TITLE
Add DSBR Twitter to config.yml

### PR DESCRIPTION
**Pull request by filipelinhares**

### CODE REVIEW

**Comment by cuducos** [comment]
What about using Operação Serenata de Amor and our the URL of the website in the config? Or maybe the Facebook URL as we hardly ever use Twitter?

**Comment by filipelinhares** [comment]
I agree with you @cuducos.

1. Change the `url` to - https://serenatadeamor.org
2. Change Twitter to FB - https://www.facebook.com/operacaoSerenataDeAmor
3. Change to version [v.1.0.0](https://github.com/datasciencebr/serenata-website/releases/tag/v1)

What do you think?

**Comment by cuducos** [comment]
Great!

**Comment by anaschwendler** [comment]
can I merge it? <3

**Comment by cuducos** [comment]
> can I merge it? <3

I don't think so. The changes discussed here were not committed yet ; )

**Comment by filipelinhares** [comment]
Done!

**Pull request merged**
