### PR TITLE
New Website - WIP

### PR DESCRIPTION
**Pull request by thulioph**
**Link to issue:**

- https://github.com/datasciencebr/serenata-website/issues/43

**How to test:**

1 - Clone the project and get into the folder:

```
$ git clone git@github.com:datasciencebr/serenata-website.git
$ cd serenata-website
```

2 - Check out the PR:

```
$ git checkout -b thulioph-next next
```

3 - Run the project:

```
$ bundle install
$ jekyll server
```

**Description of your solution:**

- Following the best practices of javascript code execution, we moved all the scripts tag to the footer with the [`async`](https://caniuse.com/#feat=script-async) attribute.

- I've split the SASS code into small parts, starting with `_variables.scss` that manages all CSS variables like, colors, font-definitions, etc. And `_grid.scss` that manages how the grid system works with Flexbox.

### CODE REVIEW

**Comment by thulioph** [comment]
I think that we can make a good code reuse if we create our components followed by this mindset:

### card-component.html

```html
<aside class="card-component"></aside>
<aside class="card-component is-active"></aside>
```

### _fragments.scss

```css
.box {
    width: 200px;
    height: 200px;
}

.rounded {
    border-radius: 12px;
}

.pink {
    background-color: pink;
}

.red {
    background-color: red;
}

.m1 {
    margin: 10px;
}

.has-border {
    border: 1px solid black;
}
```

### _components.scss

```css
.card-component {
    @extends .box;
    @extends .rounded;
    @extends .pink;
    @extends .m1;

    &.is-active {
        @extends .red;
        @extends .has-border;
    }
}
```

Instead of having, a lot of classes in the HTML markup, we can create descriptive classes and change their functionality just in CSS file. 

Thinking on [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle), we can focus the HTML structure to be easy to read and identify the components, while the CSS is just for presentation, allowing us to reuse with `@extends` easily.

What do you think about, does it make sense?

Thanks!

**Comment by cuducos** [comment]
Hi @thulioph! I really like this PR — the strategy to break up the CSS in smaller (rather semantic) SCSS files is much appreciated as well as your approach to CSS classes (basically the last comment). It's a really good job!

**Comment by cuducos** [comment]
@thulioph Years ago I started to see some debates on CSS architecture that basically tended to define one `font-size` (usually for the `body`) and all the rest tended to be relative to it using `rem` units. Surely `@media` could be used to define different `body { font-size: … }` for different medias, but anyway… what do you think about it?

Another doubt: what about including the Google Analytics *only* when deploying to production (with `JEKYLL_ENV=production jekyll build`)? Any pros or cons?

**Comment by anaschwendler** [comment]
Hi @thulioph, I tested your PR now :)

the only thing in your testing routine is that is missing the command to get into the folder:
```console
$ cd serenata-website
```

and the checkout command is inversed:
```console
$ git checkout -b thulioph-next next
```

As @cuducos I really liked that approach:

>  I really like this PR — the strategy to break up the CSS in smaller (rather semantic) SCSS files is much appreciated as well as your approach to CSS classes (basically the last comment). It's a really good job!

> Another doubt: what about including the Google Analytics only when deploying to production (with JEKYLL_ENV=production jekyll build)? Any pros or cons?

I agree with that, because we can only use the Analytics for production results, not getting from other addresses.

Is there more things you plan to do with this PR @thulioph?
I was testing its responsivity and it completely makes sense, and I think we can add to the project right now, as new structure :)

**Comment by giovanisleite** [comment]
Great work!

Just a question, @thulioph the pieces of commented out code can be removed or they will be used?

**Comment by thulioph** [comment]
> Years ago I started to see some debates on CSS architecture that basically tended to define one font-size (usually for the body) and all the rest tended to be relative to it using rem units. Surely @media could be used to define different body { font-size: … } for different medias, but anyway… what do you think about it?

I already saw something about it and it's a good idea. We can define a base value for the `font-size` on `body` and if we need to change just make it in one place and everything will follow. I can apply this approach to help us with the responsive design, but it depends on how the layout will be.  BTW, with **SASS** we can make something like [this](https://css-tricks.com/snippets/sass/px-to-em-functions/) to convert `px` to `em` values.

> Another doubt: what about including the Google Analytics only when deploying to production (with JEKYLL_ENV=production jekyll build)? Any pros or cons?

I'm not sure, but I think that the google analytics doesn't collect metrics when we're working in the development mode. What's the purpose to change it?

Cc: @cuducos

**Comment by thulioph** [comment]
Hey @anaschwendler, thank you for your feedback.

If we divide the next steps into **two parts**:

## Implementation of new design - HTML and CSS

- [ ] Set some base values like `variables`, `colors`, `grid position`, etc.
- [ ] Continue with the development of new components like `navbar`, `cards`, `footer`, etc.
- [ ] Apply some component interactions like `hover`, `loading`, `animations` and stuff like that.

## Removing the unnecessary libraries - JS

- [ ] Rewrite the javascript code to work without jQuery.

What do you think about this "roadmap"? Do you have any suggestions?

Thanks.

**Comment by thulioph** [comment]
Hey, @giovanisleite I'll use to get the data for the new layout.  It's a work in progress but will be removed in next commits.

Thanks.

**Comment by cuducos** [comment]
> I'm not sure, but I think that the google analytics doesn't collect metrics when we're working in the development mode. What's the purpose to change it?

If it doesn't send data to Google when running on `localhost` thats fine ; )

**Comment by cuducos** [comment]
Hi @thulioph — not sure if I've ever said that, but thanks for leading the new site development! We all are very glad about it 🎉 

I see the WIP label but I would like to be able to merge your work into `next` so it'd be easier for other people to join you in this task. Do you have any milestone in mind before you consider this ready for further code review and merge?

cc @cabral (who asked my how to contribute to the new website development)

**Comment by anaschwendler** [comment]
Hi @thulioph !

Sorry for my delay, but I completely agree with your roadmap :)
We can totally follow this.

As @cuducos said, thank you very much for leading our new website. It is really helping us to focus in deliver more things <3

**Comment by anaschwendler** [comment]
If @thulioph has no more things to add, I would like to test as the way it looks right now, so we can open a new PR and separate things

**Comment by cuducos** [comment]
> If @thulioph has no more things to add

AFAIK he has. @giovanisleite [asked about about the commented blocks](https://github.com/datasciencebr/serenata-website/pull/44#issuecomment-345773703) and @thulioph [said he's keeping them to make it easy to access _old_ contents](https://github.com/datasciencebr/serenata-website/pull/44#issuecomment-346506223), but that he's removing them soon.

I do agree with Giovani: this is totally fina for a WIP, but I wouldn't merge the commented blocks. if it's a matter of accessing old version of code Git handles that ; )

**Comment by thulioph** [comment]
> Hi @thulioph — not sure if I've ever said that, but thanks for leading the new site development! We all are very glad about it 🎉

Hi @cuducos, I'm so happy to may help! 😃 

> I see the WIP label but I would like to be able to merge your work into next so it'd be easier for other people to join you in this task. Do you have any milestone in mind before you consider this ready for further code review and merge?

I haven't idea about which milestone we can use, I never used it. 
Do you have any suggestions?

Thanks!

**Comment by thulioph** [comment]
> I do agree with Giovani: this is totally fina for a WIP, but I wouldn't merge the commented blocks. if it's a matter of accessing old version of code Git handles that ; )

Yes, the commented code it was removed and @anaschwendler can test it now.

**Comment by thulioph** [comment]
What do you think, about creating a new file like a `CONTRIBUTING.md` with the steps to submit a new pull request? Currently, we don't have it and it's very important rules to follow when the project is open.

## Contributing

1. Fork it!
2. Create your feature branch: `git checkout -b my-new-feature`
3. Commit your changes: `git commit -m 'Add some feature'`
4. Push to the branch: `git push origin my-new-feature`
5. Submit a pull request :D

> It's a common template.

## Coding Styles

Another "rule" to follow, is the [EditorConfig](http://editorconfig.org/). 
It helps us, to define consistent coding styles between different editors and IDEs. 

If it's ok, we can add more steps for our roadmap to add these items.

Thanks!

**Comment by anaschwendler** [comment]
Hi @thulioph!

Already tested your PR. I thought that we would make the enhancement for the website as it is right now, and then start working on the new one. But now, I think the best way is to get something consistent to the `next` branch. What do you think @cuducos?

I see that you have developed a beginning of the new one, good :)

We can divide the home page in its sections to the PRs, like this one can finish with the menu completed. Once merged, we can open a PR with the next section, so we don't have a lot of changes in one PR, what do you think, looks good?

> I haven't idea about which milestone we can use, I never used it.
Do you have any suggestions?

I think that here @cuducos was talking about setting some endpoints so other don't bother in the part that you are developing, because they where are you going and where to start developing something, and no one develop the same thing.

> What do you think, about creating a new file like a CONTRIBUTING.md with the steps to submit a new pull request?

Sure, we can totally do that, the best way is creating a issue for that :)

**Comment by cuducos** [comment]
Hi @thulioph — let me try to clarify what I was saying…

We don't have any _specific_ milestone in mind. But we have more people (me included) willing to help in coding this website. So it's not a good strategy to keep everything in your branch until we have 100% done, and just then review and merge.

I would like to see the basic stuff merged to `next` so more people can open PR to `next` continuing what you've started. 

So what I would like to hear from you is when you're comfortable with this PR so we can merge it to `next`. This way more people can jump in and code over the beautiful structure you're putting forward.

Does that make sense?

**Comment by notnotgabriel** [comment]
Hello everyone! I would like to help on this new version of the website.
What is the actual status?

**Comment by cuducos** [comment]
Hi @notnotgabriel – many thanks for your enthusiasm. Unfortunately we had to unprioritize this new version of the website to focus on other projetcs. I'm afraid the status is… idle.

**Comment by notnotgabriel** [comment]
@cuducos Ahh ok. I'll be watching the project.
Let me know if you all need some help with front-end.

**Comment by cuducos** [comment]
Closed/archived by inactivity.

**Pull request closed without merging**
