### PR TITLE
Hover area on footer anchor tag - Solve

### PR DESCRIPTION
**Pull request by lucasdutraf**
#### Link to issue:
#60 

#### What is the purpose of this Pull Request?
When we entered the serenata's website, we noticed that the anchor tag hover effect was not behaving as expected, the action area was much bigger than the actual text.

#### What was done to achieve this purpose?
We added classes for each link, limiting the width of the action area to match the text.

#### How to test if it really works?
Clone the repo, run the project and go to the main page's footer to check the anchor tags updated hover effects. 

#### Who can help reviewing it?
Anyone! :smile_cat: 

Special thanks to @youssef-md who helped a lot with his css knowledge and @RochaCarla to present us the open source world. 
This is our first contribution to a big open source project, we hope that we helped and suggestions are welcome!

### CODE REVIEW

**Comment by youssef-md** [comment]
The footer area need a general refactoring and enhancement, to improve the maintainability and the responsiveness, this contribution can be the start of a relationship with the project. 😄

**Comment by cuducos** [comment]
[content moved to the review block]

**Review by cuducos — CHANGES_REQUESTED** [review]
Hi @lucasdutraf, many thanks for the contribution.

> We added classes for each link, limiting the width of the action area to match the text.

I think this was a bit over engineering and might be a risky implementation: defining fixed widths for the link is a fix for an issue that might be avoided. So why not avoid the issue instead of creating it and then fixing it?

To be precise: link areas are bigger than text because the `a` nodes are marked as `display: block` in the CSS, so they are bigger then the text node inside it. What about removing the `display: block` so the text and the link area match each other?

Surely we need something else: maybe a `br` tag after the `a` tags, maybe some CSS magic in the `a:after` selector, maybe using `inline-block` instead of `block`…

What do you think?

**Comment by youssef-md** [comment]
We tried to avoid hard coding the values, but we were not understanding the general CSS that was already there, but thanks for the suggestions we will definitely improve that.

**Comment by lucasdutraf** [comment]
> We tried to avoid hard coding the values, but we were not understanding the general CSS that was already there, but thanks for the suggestions we will definitely improve that.

As @youssef-md said, we had problems with bootstrap base styles, if i'm not wrong. It is funny that you said about the ```display: block```, because we spent hours trying to figure out what cannot let us use ```inline-block``` and hard-coding each link tag was the only capable solution we figured out. But we will take a better look at the code and improve our pull request, thanks a lot for the review and the suggestions @cuducos ! :heart:

**Comment by youssef-md** [comment]
@lucasdutraf and I found a simpler solution for this issue, using ```display: table```, it makes the anchor tag occupies only the needed space for each tag content.

**Pull request merged**
