### PR TITLE
Menu Typo

### PR DESCRIPTION
**Pull request by raimundonorberto**

### CODE REVIEW

**Comment by cuducos** [comment]
I'm a bit confused… wasn't that fixed by #27? Why isn't it on `master`… I don't get it. Anyone? cc @anaschwendler

**Comment by anaschwendler** [comment]
Sorry by my lateness, I'm here to check it, @cuducos did you run `jgd` after merging it?

**Comment by anaschwendler** [comment]
I'll merge it and run `jgd` to get on the website!
Thanks for helping us!

**Comment by anaschwendler** [comment]
Fixed it ;)

**Pull request merged**
